CREATE TABLE services (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service TEXT NOT NULL,
    price TEXT NOT NULL
);

INSERT INTO services 
(service, price)
VALUES
('Basement', '40'),
('Bathroom', '30'),
('Bed rooms', '30'),
('Den', '25'),
('Dining room', 
'25'),
('Glass doors / Windows', '15'),
('Kitchen', '25'),
('Living room', '35');
